hash-format = "sha256"

[[files]]
file = "mods/appleskin.pw.toml"
hash = "417e4f42790407e6fb4dfcb03cd4abcdf3aa00f4dcef3f3a2edec1a3e1a9a3ef"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "848c49f2ead5e1e71d7be95d2d9e1cb992631faf91500b9c59e72d61afca33fd"
metafile = true

[[files]]
file = "mods/axiom.pw.toml"
hash = "db2e743bc9073a17571721ecad0b8ac774769db5cada2a483752cc8ae92413ca"
metafile = true

[[files]]
file = "mods/betterf3.pw.toml"
hash = "cbc0973dadd8e4a191ce8e819f212bcfb58708885b4a46a9de7afa29e71aadad"
metafile = true

[[files]]
file = "mods/bobby.pw.toml"
hash = "783f6391e53272943cce060fd820d1c5b7cbdf94df1341f250bf09eaa296171c"
metafile = true

[[files]]
file = "mods/carpet.pw.toml"
hash = "34f76ee3754c91d7493931fdf0df27e8788b336277efc90ced549ec27a1fc5b7"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "df15648dd4d4e27dd0c45ab4e78277c45886b77a698b129f4ce2d2bc337f7044"
metafile = true

[[files]]
file = "mods/dynamic-fps.pw.toml"
hash = "04851cf23a0fef9e213180bf5926b705c5ad2d0b04d41934b915cc1ccfabd841"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "b2f2ef63febe17f277635827ca474e1aeae321e8a82bef78942116f95d00250a"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "d7c055f277c1751122d9abc5f09015e629699e04a9383cd0c666b33436293079"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "e03fc0b0c151c5c072ac399d27b5c4268a093c41be73f3b1578d050bb49211f3"
metafile = true

[[files]]
file = "mods/krypton.pw.toml"
hash = "c4e45594c8d1ab3dacc3b49142f16fb253178dd31d97cc917bf4a4d54f21e081"
metafile = true

[[files]]
file = "mods/lambdynamiclights.pw.toml"
hash = "06d953295265b2f415532373736703632cbddcfe916a8f6534ab3006f57a6c4f"
metafile = true

[[files]]
file = "mods/litematica.pw.toml"
hash = "0f7f066cbccb9fcdb21bc77884aaeb05402f192aaa0c6dd2c9f3ab22c7425ce4"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "df9d69dc784ef61e99064407952d34c294f62fe1155b5260f825bd9a82e2f3a2"
metafile = true

[[files]]
file = "mods/malilib.pw.toml"
hash = "bc2593ee70b981e2b23074ff2ef9a074c15aecdc6f4ac35ca2d96a56dddf6e1e"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "88c6edc1712f4f0cd915cd723b9e0296924d454b3855a719d2962103b2b92bea"
metafile = true

[[files]]
file = "mods/no-chat-reports.pw.toml"
hash = "95ff1073b74b23e62cae94569ffb63e6e2f244d99a6d1a38c4a26bdd183a64eb"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
hash = "55a727cabdd9d6e84fb0232b49d0dfa207751002e7f1f63b959baa35e2f29868"
metafile = true

[[files]]
file = "mods/replaymod.pw.toml"
hash = "e70e8529c163ced6575c52810ed56b7dbe2fdf7348111680c82e1f411c52f3ed"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "56a0e243140dc1dbdb89c5a7a1cbcbe6e8d6da5499242bd1eabf548bbb8e3481"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "09d2dbee70e91e8859e6f62e4181a80264d6dd24cc686fbedb93dda9f69fdfe6"
metafile = true

[[files]]
file = "mods/stendhal.pw.toml"
hash = "ef09549b50c6d26e7796f9019c7af46bf0b90fd89362286325030194373ada82"
metafile = true

[[files]]
file = "mods/tweakeroo.pw.toml"
hash = "24c09cf676943991397e15eba13c14598dbe3575cf025abcebb22947c450febf"
metafile = true

[[files]]
file = "mods/viafabricplus.pw.toml"
hash = "d5a6f65c0a04360a54bf687bcdc429d5ff9399c15e832e9f6a43efcbfba2ec01"
metafile = true

[[files]]
file = "mods/worldedit.pw.toml"
hash = "27d8566cfd4ee1f34979f92b22dbd2d205f30f8190329c5335425c951ca9f0f9"
metafile = true

[[files]]
file = "mods/xaeros-world-map.pw.toml"
hash = "3f60bc88727210061f2ed50591a235e2e1ad78f5363150a7b33fc2862e2d31a5"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "df3e6006edbb3bb75303bbb2e2bb971fe8f228b548d07bd7e0c1aa44e18ef67b"
metafile = true

[[files]]
file = "mods/zoomify.pw.toml"
hash = "c9a5dca078d983e94d629ca4bf402fff78e364e5b5365ff43373d77eec268432"
metafile = true

[[files]]
file = "shaderpacks/complementary-reimagined.pw.toml"
hash = "531a8d239c952428d9a633ff99cb03461656ada28decbe2e1ef19f60f7fd5726"
metafile = true

[[files]]
file = "shaderpacks/rethinking-voxels.pw.toml"
hash = "0a3f01f56afd065dc65dffb073b4fc5f9ae031aaef08d95d9df92e0093ac8504"
metafile = true
